# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
    -   id: fmt-check
    -   id: check
    -   id: clippy
    -   id: test
