[package]
name = "permafrust"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Krennwallner <tk@postsubmeta.net>"]
description = "Backup and restore tool for remote off-site backups"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tkren/permafrust"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "~0.8.1", features = ["ssh"] }
aws-config = "~0.46.0"
aws-sdk-s3 = "~0.16.0"
aws-types = "~0.46.0"
clap = { version = "~3.2.15", features = ["cargo", "derive"] }
crossbeam-channel = "~0.5.6"
env_logger = "~0.9.0"
futures = "~0.3.21"
log = "~0.4.17"
lz4_flex = "~0.9.4"
notify = "~5.0.0-pre.15"
parse-size = "~1.0.0"
retry = "~1.3.1"
serde = "~1.0.140"
serde_derive = "~1.0.140"
sequoia-sop = "~0.27.1"
sequoia-openpgp = "~1.10.0"
thiserror = "~1.0.31"
time = "~0.3.11"
tokio = { version = "~1.20.1", features = ["full"] }
toml = "~0.5.9"
uuid = { version = "~1.1.2", features = ["serde"] }
xdg = "~2.4.1"
zstd = "~0.11.2"

[dev-dependencies]
tempfile = "~3.3.0"

[profile.release]
strip = "debuginfo"
