[package]
name = "permafrust"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Krennwallner <tk@postsubmeta.net>"]
description = "Backup and restore tool for remote off-site backups"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tkren/permafrust"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "~0.9.2", features = ["ssh"] }
anyhow = { version = "~1.0.75", features = ["backtrace"] }
aws-config = "~0.56.1"
aws-sdk-s3 = "~0.34.0"
aws-types = "~0.56.1"
clap = { version = "~4.4.7", features = ["cargo", "derive"] }
crossbeam = "~0.8.2"
crossbeam-utils = "~0.8.16"
env_logger = "~0.10.0"
futures = "~0.3.29"
log = "~0.4.20"
lz4_flex = "~0.11.1"
notify = "~6.1.1"
nix = { version = "~0.27.1", features = ["fs"] }
parse-size = "~1.0.0"
retry = "~2.0.0"
rpassword = "~7.2.0"
serde = "~1.0.190"
serde_derive = "~1.0.190"
sequoia-openpgp = "~1.17.0"
thiserror = "~1.0.50"
thread_io = "~0.3.1"
time = "~0.3.30"
tokio = { version = "~1.33.0", features = ["full"] }
toml = "~0.8.6"
uuid = { version = "~1.5.0", features = ["serde"] }
xdg = "~2.5.2"
walkdir = "~2.4.0"
zstd = "~0.13.0"

[dev-dependencies]
tempfile = "~3.8.1"

[profile.release]
strip = "debuginfo"
