[package]
name = "permafrust"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Krennwallner <tk@postsubmeta.net>"]
description = "Backup and restore tool for remote off-site backups"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tkren/permafrust"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "~0.9.2", features = ["ssh"] }
anyhow = { version = "~1.0.72", features = ["backtrace"] }
aws-config = "~0.56.0"
aws-sdk-s3 = "~0.29.0"
aws-types = "~0.56.0"
clap = { version = "~4.3.21", features = ["cargo", "derive"] }
crossbeam = "~0.8.2"
crossbeam-utils = "~0.8.16"
env_logger = "~0.10.0"
futures = "~0.3.28"
log = "~0.4.19"
lz4_flex = "~0.11.1"
notify = "~6.0.1"
parse-size = "~1.0.0"
retry = "~2.0.0"
serde = "~1.0.183"
serde_derive = "~1.0.183"
sequoia-openpgp = "~1.16.0"
thiserror = "~1.0.44"
thread_io = "~0.3.1"
time = "~0.3.25"
tokio = { version = "~1.30.0", features = ["full"] }
toml = "~0.7.6"
uuid = { version = "~1.4.1", features = ["serde"] }
xdg = "~2.5.2"
walkdir = "~2.3.3"
zstd = "~0.12.4"

[dev-dependencies]
tempfile = "~3.7.1"

[profile.release]
strip = "debuginfo"
