[package]
name = "permafrust"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/tkren/permafrust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.34.0"
crossbeam-channel = "~0.5.1"
env_logger = "~0.9.0"
log = "~0.4.14"
lz4_flex = "~0.9.2"
notify = "~5.0.0-pre.13"
rusoto_dynamodb = "~0.47.0"
rusoto_glacier = "~0.47.0"
sequoia-openpgp = "~1.6.0"
serde = "~1.0.117"
sha2 = "~0.9.8"
xdg = "~2.4.0"
zstd = "~0.9.0"

[dev-dependencies]
tempfile = "~3.2.0"
