[package]
name = "permafrust"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Krennwallner <tk@postsubmeta.net>"]
description = "Backup and restore tool for remote off-site backups"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tkren/permafrust"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "~0.13.0"
aws-sdk-s3 = "~0.13.0"
chrono = "~0.4.19"
clap = { version = "~3.1.18", features = ["cargo", "derive"] }
crossbeam-channel = "~0.5.4"
env_logger = "~0.9.0"
log = "~0.4.17"
lz4_flex = "~0.9.3"
notify = "~5.0.0-pre.15"
parse-size = "~1.0.0"
sequoia-openpgp = "~1.9.0"
serde = "~1.0.137"
sha2 = "~0.10.2"
thiserror = "~1.0.31"
tokio = { version = "~1.19.2", features = ["full"] }
uuid = "~1.1.2"
xdg = "~2.4.1"
zstd = "~0.11.2"

[dev-dependencies]
tempfile = "~3.3.0"

[profile.release]
strip = "debuginfo"
