[package]
name = "permafrust"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/tkren/permafrust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.0"
crossbeam-channel = "~0.4.0"
env_logger = "~0.9.0"
log = "~0.4.14"
notify = "~5.0.0-pre.13"
rusoto_dynamodb = "~0.47.0"
rusoto_glacier = "~0.47.0"
sequoia-openpgp = "~1.4.0"
sha2 = "~0.9.8"

[dev-dependencies]
tempfile = "~3.2.0"
