[package]
name = "permafrust"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Krennwallner <tk@postsubmeta.net>"]
description = "Backup and restore tool for remote off-site backups"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tkren/permafrust"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "~0.9.0", features = ["ssh"] }
anyhow = { version = "~1.0.68", features = ["backtrace"] }
aws-config = "~0.52.0"
aws-sdk-s3 = "~0.22.0"
aws-types = "~0.52.0"
clap = { version = "~4.0.32", features = ["cargo", "derive"] }
crossbeam = "~0.8.2"
crossbeam-utils = "~0.8.14"
env_logger = "~0.10.0"
futures = "~0.3.25"
log = "~0.4.17"
lz4_flex = "~0.9.5"
notify = "~5.0.0"
parse-size = "~1.0.0"
retry = "~2.0.0"
serde = "~1.0.151"
serde_derive = "~1.0.151"
sequoia-openpgp = "~1.12.0"
thiserror = "~1.0.38"
thread_io = "~0.3.0"
time = "~0.3.17"
tokio = { version = "~1.23.0", features = ["full"] }
toml = "~0.5.10"
uuid = { version = "~1.2.2", features = ["serde"] }
xdg = "~2.4.1"
zstd = "~0.12.1"

[dev-dependencies]
tempfile = "~3.3.0"

[profile.release]
strip = "debuginfo"
