name: security

on:
  schedule:
    - cron: "4 2 * * *"

  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: rustsec/audit-check@286a088f1cead63b54654692f8b045680f8f805f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: RUSTSEC-2023-0071
