name: security

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    paths:
      - "**/Cargo.*"

  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
